name = "asndb"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "b0d7b9f87b57470ef508f1a511093cae"

routes = [
    { pattern = "asndb.network/*", zone_id = "7c37cd82c1529fcb49c66e21bf64230f" }
]

[[kv_namespaces]]
binding = "asndb"
id = "97af583cd69f4d7b8a060f8915ee3d24"

[assets]
directory = "assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "R2"
bucket_name = "asndb"
